name: Docker
on:
  push:
  pull_request:
  release:
    types:
      - published
      - released

jobs:
  multi:
    name: "Multi"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the container image
        uses: docker/build-push-action@v1
        with:
          repository: test-github-actions

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        if: github.event_name == 'release' || contains(github.ref, "ref/head/v*")
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: moul/test-github-actions/test-github-actions
          tag_with_ref: true

      - name: Check Docker Hub Credentials
        id: check_dockerhub_credentials
        if: github.event_name == 'release' || contains(github.ref, "ref/head/v*")
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          if [ "${DOCKER_USERNAME}" == "" ]; then
            echo "Missing Username"
            echo "##[set-output name=missingsecrets;]$(echo yes)"
          elif [ "${DOCKER_PASSWORD}" == "" ]; then
            echo "Missing Password"
            echo "##[set-output name=missingsecrets;]$(echo yes)"
          else
            echo "All secrets present"
            echo "##[set-output name=missingsecrets;]$(echo no)"
          fi

      - name: Push to Docker Hub
        if: |
          (github.event_name == 'release' || contains(github.ref, "ref/head/v*")) &&
          contains(steps.check_dockerhub_credentials.outputs.missingsecrets, 'no')
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: moul/test-github-actions
          tag_with_ref: true
